### ISSUE TITLE
Plugin doesn't work with version 1.9 of Discourse

### ISSUE THREAD

**Issue by magne4000** [auth0/discourse-plugin#30]
With latest discourse (1.9 beta 13) this plugin doesn't seem to work.
After login into auth0, I'm redirected to the "Create an account" popup, empty.

**Comment by chard234** [comment]
I am experiencing the same empty pop-up problem.  I have tried rolling back to v1.7.8  of Discourse but I am still experiencing the empty popup.  Have you had any success in getting the plugin to work?

**Comment by magne4000** [comment]
@chard234 I fixed it here https://github.com/getstation/discourse-plugin/

**Comment by chard234** [comment]
@magne4000 Thanks for taking a look but the linked plugin doesn't seem to do the job.

When using the plugin I get the option to use Auth0 when clicking 'Log In', however when chosen the pop-up reads 'Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?'

Looking at the logs (production.logs)
Started GET "/auth/auth0" for 31.51.21.216 at 2017-11-02 17:04:48 +0000
(auth0) Request phase initiated.
(auth0) Authentication failure! missing_client_id encountered.
Started GET "/auth/failure?message=missing_client_id&strategy=auth0" for 31.51.21.216 at 2017-11-02 17:04:48 +0000
Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"message"=>"missing_client_id", "strategy"=>"auth0"}

In the Discourse settings I have entered the appropriate strings into the Auth0 plugin.  Do i need to change anything else to get this to work? I noticed you removed the auth0_connection, is this part of the problem?

In terms of the Auth0 client, I have used a 'Regular Web Application', 'Token Endpoint' as Post, copied over the allowed callback from the one edited in Discourse Auth0 plugin.

Is it a problem on my end?

**Comment by magne4000** [comment]
@chard234 yeah had the same issue, restarting the discourse instance solved it.

**Comment by chard234** [comment]
@magne4000 I have tested on a fresh standalone discourse instance.  Still having the same issues, did you do anything other than restart the instance to get it to work?

**Comment by magne4000** [comment]
@chard234 I did a small update, could you try again ?

**Comment by chard234** [comment]
@magne4000 The newest version did not compile, however I just needed to change the references from options. to SiteSetting.

Thanks for the help! You massively sped up this project!

**Comment by arquio** [comment]
My error log testing the @magne4000 repo with the fix: 
`I, [2017-11-07T10:38:45.689223 #15]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
SyntaxError: /var/www/discourse/plugins/discourse-plugin/plugin.rb:63: syntax error, unexpected tSYMBEG, expecting ']'
    :client_secret
     ^
/var/www/discourse/plugins/discourse-plugin/plugin.rb:65: syntax error, unexpected ']', expecting keyword_end
/var/www/discourse/lib/plugin/instance.rb:412:in `instance_eval'
/var/www/discourse/lib/plugin/instance.rb:412:in `activate!'
/var/www/discourse/lib/discourse.rb:146:in `block in activate_plugins!'
/var/www/discourse/lib/discourse.rb:143:in `each'
/var/www/discourse/lib/discourse.rb:143:in `activate_plugins!'
/var/www/discourse/config/application.rb:178:in `<class:Application>'
/var/www/discourse/config/application.rb:26:in `<module:Discourse>'
/var/www/discourse/config/application.rb:25:in `<top (required)>'
/var/www/discourse/Rakefile:5:in `require'
/var/www/discourse/Rakefile:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'`

Thanks for all

**Comment by magne4000** [comment]
@arquio ah yes, I forgot 2 commit my last fix, you should be good now

**Comment by arquio** [comment]
I tried it and it seems that everything is fine!

Thaks a lot!!

**Comment by efuetatem** [comment]
Hello,

We are using your plugin with Discourse (v1.9.0.beta15). When the user logs in, he/she is redirected to the 'Create new account' popup of Discourse with the pre-filled Email / Username / and Name fields instead of he/she being connected to Discourse. Auth0 logs indicate that the user is connected to Auth0. Using Firebug, we can clearly see that Discourse retrieves the session of the user.

The documentation of Lock 10 says that we have to listen to the event 'authenticated' in order to retrieve the user's connection (ex: lock.on("authenticated", function(authResult) { .... } ) In your code, I can't see this event, is that normal?

The plugin (https://github.com/leog/Discourse-App-Auth0-Plugin/blob/master/assets/javascripts/auth0.js) seems to use this event. Unfortunately, we couldn't make it work either.

thank you very much for your help

**Comment by efuetatem** [comment]
@magne4000 Hello Charles, I don't know if you can be of help...
Thanks in advance
